###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
sr: 24000     # Sampling rate.
n_fft: 2048           # FFT size.
hop_length: 300            # Hop size.
win_length: 1200         # Window length.
                         # If set to null, it will be the same as fft_size.
window: "hann"           # Window function.
n_mels: 80             # Number of mel basis.
fmin: 80                 # Minimum freq in mel basis calculation.
fmax: 7600               # Maximum frequency in mel basis calculation.
# global_gain_scale: 1.0   # Will be multiplied to all of waveform.
trim_silence: false      # Whether to trim the start and end of silence.
top_db: 60 # Need to tune carefully if the recording is not good.
trim_frame_length: 2048    # Frame size in trimming.(in samples)
trim_hop_length: 512       # Hop size in trimming.(in samples)


###########################################################
#                       DATA SETTING                      #
###########################################################
batch_size: 32
num_workers: 4




###########################################################
#                       MODEL SETTING                     #
###########################################################
model:
  vocab_size: 101 # 99 + 2
  tone_size: 8 # 6 + 2
  encoder_hidden_size: 128
  encoder_kernel_size: 3
  encoder_dilations: [1, 3, 9, 27, 1, 3, 9, 27, 1, 1]
  duration_predictor_hidden_size: 128
  decoder_hidden_size: 128
  decoder_output_size: 80
  decoder_kernel_size: 3
  decoder_dilations: [1, 3, 9, 27, 1, 3, 9, 27, 1, 3, 9, 27, 1, 3, 9, 27, 1, 1]


###########################################################
#                     OPTIMIZER SETTING                   #
###########################################################


###########################################################
#                     TRAINING SETTING                    #
###########################################################
max_epoch: 300
num_snapshots: 5


###########################################################
#                       OTHER SETTING                     #
###########################################################
seed: 10086